# Generated by Django 3.1.7 on 2021-06-20 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_auto_20210620_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='roles',
            field=models.ManyToManyField(related_name='profile_roles', to='API.Role'),
        ),
    ]
