# Generated by Django 3.1.7 on 2021-07-11 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_auto_20210620_2255'),
    ]

    operations = [
        migrations.CreateModel(
            name='Victim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expedient_number', models.CharField(max_length=70)),
                ('name', models.CharField(max_length=70)),
                ('second_name', models.CharField(max_length=70)),
                ('lastname', models.CharField(max_length=70)),
                ('birthdate', models.DateField()),
                ('age', models.IntegerField()),
                ('address', models.CharField(max_length=500)),
                ('occupation', models.CharField(max_length=70)),
                ('phone_number', models.CharField(max_length=70)),
                ('phone_number2', models.CharField(max_length=70)),
                ('email', models.CharField(max_length=70)),
                ('reference', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
