# Generated by Django 3.1.7 on 2021-07-20 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0008_anamnesis'),
    ]

    operations = [
        migrations.CreateModel(
            name='PsychologicalReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motive', models.CharField(max_length=200)),
                ('instruments', models.CharField(max_length=5000)),
                ('genogram', models.CharField(max_length=500)),
                ('personal_ant', models.CharField(max_length=500)),
                ('familiar_ant', models.CharField(max_length=500)),
                ('general_imp', models.CharField(max_length=500)),
                ('mental_exam', models.CharField(max_length=500)),
                ('results', models.CharField(max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
